name: Tests
on: [push]
env:
  JSON_RPC: ${{ secrets.JSON_RPC }}
  ALCHEMY_MAINNET: ${{ secrets.ALCHEMY_MAINNET }}
  ALCHEMY_ARBITRUM: ${{ secrets.ALCHEMY_ARBITRUM }}
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          # Needed for commands that depend on git tags
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          yarn
      - name: Prettier
        run: |
          yarn prettier
      - name: Lint
        run: |
          yarn lint
      - name: Compile contracts
        run: |
          yarn compile
      - name: 💡 Run contract tests, except mainnet
        run: |
          yarn test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  mainnet-fork:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v2 
        with:
          # Needed for commands that depend on git tags
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          yarn
      - name: Compile contracts
        run: |
          yarn compile
      - name: 💡 Run contract mainnet tests
        run: |
          yarn test:mainnet
